### ISSUE TITLE
iPhone SE part 1

### ISSUE THREAD

**Issue by annikajun** [annikajun/Portfolio_2023#11]
The Download CV button is too low, ✅fixed
there is a weird white space on the home page and 
the footer is stuck in the middle on the project page

**Comment by Dominickstephens** [comment]
The Download CV button is too low, ✅fixed
there is a weird white space on the home page and
the footer is stuck in the middle on the project page, ✅ fixed

**Comment by annikajun** [comment]
The Download CV button is too low, ✅fixed
there is a weird white space on the home page (section snap not working) and REFERRED
the footer is stuck in the middle on the project page ✅ fixed
